version: "2"

services:
  nginx:
    build: ./nginx
    image: ghcr.io/groskopf/printerboks_nginx:1.2
    env_file:
      - ./config.env
    volumes:
      - nginx_conf:/etc/nginx/sites
      - nginx_ssl:/etc/nginx/ssl
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
      - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    build: ./certbot
    image: ghcr.io/groskopf/printerboks_certbot:1.1
    env_file:
      - ./config.env
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
    depends_on:
      - nginx

  cron:
    build: ./cron
    image: ghcr.io/groskopf/printerboks_certbot_cron:1.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
    depends_on:
      - nginx
      - certbot

volumes:
  nginx_conf:
  nginx_ssl:
    external: true
  letsencrypt_certs:
    external: true
  certbot_acme_challenge:
